pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./activities_intro.html","Activities: Introduction","The Activity class is a crucial component of an Android app. The way activities are launched and put together is a fundamental part of the platfor...",""],
["./android_appdev_top.html","Explore Android app development","This text has links to important sections of the Android documentation HTML files. ",""],
["./android_applifecycle.html","The Android app lifecycle","Introductory text here   About the Android app lifecycle Lifecycle refers to the series of states that an Android activity or fragment goes t...",""],
["./android_appresources.html","App resources","Resources are the additional files and static content that your code uses, such as bitmaps, layout definitions, user interface strings, animation ...",""],
["./android_handleconfig.html","Handle configuration changes","Enter topic text here.",""],
["./android_uicomponents.html","android_uicomponents","Enter topic text here.  Textview Buttons Radio button Toggle button Image button EditText ImageView Displays an images RecyclerView Create li...",""],
["./app_architecture.html","App architecture","Lorem ipsum dolor amet mustache knausgaard +1, blue bottle waistcoat tbh semiotics artisan synth stumptown gastropub cornhole celiac swag. Brunch ...",""],
["./app_arch_data_layer.html","App architecture &#62; Data layer","Bacon ipsum dolor amet short ribs brisket venison rump drumstick pig sausage prosciutto chicken spare ribs salami picanha doner. Kevin capicola sa...",""],
["./app_arch_domain_layer.html","App architecture &#62; Domain layer","Enter topic text here.",""],
["./app_arch_recommmends.html","App architecture &#62; Architecture recommendations","Cheese on toast airedale the big cheese. Danish fontina cheesy grin airedale danish fontina taleggio the big cheese macaroni cheese port-salut. Ed...",""],
["./app_arch_ui_layer.html","App architecture &#62; UI layer","Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo ve...",""],
["./app_fundamentals.html","Android app fundamentals","Introduction Android apps can be written using Kotlin, the Java programming language, and C++ languages. The Android SDK tools compile your code a...",""],
["./app_lifecycle_top.html","Android app fundamentals &#62; App Lifecycle","Introductory text here Overview: Building an Android app with Code on the Go Here&#39;s a high-level overview of building an Android app using Code on...",""],
["./classes.html","Java SE and API &#62; Java Platform&#174;, Standard Edition &#62; Classes","Enter topic text here.",""],
["./cogo_build_top.html","Code on the Go &#62; Build the app","Build the app Navigation: Code on the Go Build the app ",""],
["./cogo_debugger_top.html","Code on the Go &#62; Use the debugger","Enter topic text here.",""],
["./cogo_docs_top.html","Documentation and reference materials","Get help anywhere Three kinds of help are available throughout Code on the Go.  Tooltips. To display a tooltip, long-press anything on the sc...",""],
["./cogo_filetreenav.html","Code on the Go &#62; Navigating folders and files","To display and navigate the file tree for the current project, follow these steps:",""],
["./cogo_getstarted.html","Code on the Go &#62; Get started","Code on the Go delivers a full-featured IDE on a small screen. Please review terminology for different parts of the screen. ",""],
["./cogo_layouteditor_top.html","Code on the Go &#62; Use the layout editor","Enter topic text here.",""],
["./cogo_modules.html","Code on the Go &#62; Modules","Modules Overview A module is a collection of source files and build settings that let you divide your project into discrete units of functionality...",""],
["./cogo_output_top.html","Code on the Go &#62; Output panel","Enter topic text here. To view, swipe up.  Show/hide the output panel  screen cap Options include: Build output App logs IDE logs Diagno...",""],
["./cogo_preferences.html","Code on the Go &#62; Preferences","Enter topic text here.",""],
["./cogo_preferences_top.html","Code on the Go &#62; Preferences","TK week of February 4 To view the Preferences page, choose one of the following: On the Code on the Go top page, tap Preferences.  In an open...",""],
["./cogo_projects_top.html","Code on the Go &#62; Projects and templates","A project in Code on the Go contains everything that defines your workspace for an app, including source code and resources to help test and build...",""],
["./cogo_search_top.html","Code on the Go &#62; Search projects and files","You can search, summary stuff.  Find in current file Only in text editor. Tap the Search icon.  Tap Find in File. At the bottom of the s...",""],
["./cogo_texteditor_top.html","Code on the Go &#62; Use the text editor","So here&#39;s the Sora screen with a lot of stuff on it, and cool callouts. Maybe even hotspot links! ",""],
["./cogo_top.html","Code on the Go","This page is currently a mess! Need to figure out what&#39;s the right level of abstraction. Probably combine with the mess on Get started.",""],
["./get-started.html","Code on the Go &#62; Get started","What is Code on the Go? How do I get started?",""],
["./gradle_build.html","Gradle &#62; gradle_build","Enter topic text here.",""],
["./gradle_top.html","Gradle","The following Gradle resources are available:  Gradle User Manual",""],
["./java-development-kit-version-2.html","Java SE and API &#62; Java Development Kit Version 22 API Specification","Enter topic text here.",""],
["./java-sdk.html","Java SE and API &#62; Java Platform&#174;, Standard Edition","Enter topic text here.",""],
["./java-se-and-api.html","Java","Link to complex documentation Link to Java keywords",""],
["./java_base.html","Java SE and API &#62; Java Platform&#174;, Standard Edition &#62; Modules &#62; java.base","Defines the foundational APIs of the Java SE Platform.",""],
["./java_io.html","java.io","java.io Provides for system input and output through data streams, serialization and the file system. java.lang Provides classes that are fundamen...",""],
["./java_keywords.html","Java &#62; Java keywords","Java reserves the following keywords. This page is based on content from Wikipedia (https://en.wikipedia.org/wiki/List_of_Java_keywords) and from ...",""],
["./java_top.html","Java","The following Java resources are available:  Java Development Kit (JDK) documentation  Classes Packages Modules Java keywords (our page ...",""],
["./kotlin_keywords.html","Kotlin &#62; Kotlin keywords","Kotlin docs have good coverage on keywords (unlike Java) so we don&#39;t need to ",""],
["./kotlin_top.html","Kotlin","The following Kotlin resources are available:  Kotlin documentation (link to top page of their documentation).  Get started Reference ma...",""],
["./module-summary.html","java.instrument (Java SE 22 &#38; JDK 22)","JavaScript is disabled on your browser.     SKIP NAVIGATION LINKS Java SE 22 &#38; JDK 22 OVERVIEW MODULE PACKAGE CLASS USE TREE PREVIEW...",""],
["./modules.html","Java SE and API &#62; Java Platform&#174;, Standard Edition &#62; Modules","Enter topic text here.",""],
["./package-summary.html","java.io (Java SE 22 &#38; JDK 22)","declaration: module: java.base, package: java.io",""],
["./packages.html","Java SE and API &#62; Java Platform&#174;, Standard Edition &#62; Packages","Enter topic text here.",""],
["./prefs_editor.html","Editor preferences","Enter topic text here.",""],
["./using-groovy.html","Gradle &#62; Using Groovy","Enter topic text here.",""],
["./using-kotlin-script.html","Gradle &#62; Using Kotlin Script","Enter topic text here.",""],
["./whatever.html","Key Android development concepts","Key Android Development Concepts Android app development relies on the following concepts: Activities: The building blocks for screens. Fragments:...",""]];
